apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: loadtest
deploy:
  kubectl:
    manifests:
    - k8s/configmap.yaml
    - k8s/locust-master.yaml
    - k8s/locust-worker.yaml
portForward:
- resourceType: Service
  resourceName: locust-master
  namespace: default
  address: 0.0.0.0
  port: 8089
  localPort: 8089
