apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-configmap
data:
  locustfile.py: |
    from locust import FastHttpUser, between, task
    
    class QuickstartUser(FastHttpUser):

        wait_time = between(1, 3)

        @task
        def get_random_number(self):
            self.client.get("/random-number")
